Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [16]:
import numpy as np
list_ = [ '1' , '2','3','4','5' ]
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [17]:
import numpy as np
list_ = [ '1' , '2','3','4','5' ]
array_list = np.array(object = list_)
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [18]:
import numpy as np
list_ = [ '1' , '2','3','4','5' ]
array_list = np.array(object = list_)
for i in list_:
    print(type(i),end=",")
for j in array_list:
    print(type(j),end=",")


<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'numpy.str_'>,<class 'numpy.str_'>,<class 'numpy.str_'>,<class 'numpy.str_'>,<class 'numpy.str_'>,

3.Considering the following changes in the variable, array_list:

In [21]:
import numpy as np
list_ = [ '1' , '2','3','4','5' ]
array_list = np.array(object = list_, dtype = int)
array_list

array([1, 2, 3, 4, 5])

4.Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [29]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

print(num_array.size)
print(num_array.shape)

6
(2, 3)


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [34]:
import numpy as np

arr=np.zeros((3,3))
# arr.size
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [38]:
data=np.diag([1,1,1,1,1,])
data

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])